export const CommonErrorCodes = {
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  UNAUTHORIZED_OPERATION: 'UNAUTHORIZED_OPERATION',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DUPLICATED_RESOURCE: 'DUPLICATED_RESOURCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type CommonErrorCode = (typeof CommonErrorCodes)[keyof typeof CommonErrorCodes];
